language: ruby
rvm: 2.6
cache: bundler
dist: xenial
addons:
  apt:
    packages:
      - bison
      - flex
      - libffi-dev
      - libxml2-dev
      - libgdk-pixbuf2.0-dev
      - libcairo2-dev
      - libpango1.0-dev
      - fonts-lyx
before_install:
  - gem update --system
  - gem install bundler
script:
  # make html and pdf
  - make all EXTRA_ARGS="--failure-level WARN"
